# Generated by Django 3.0.3 on 2020-02-22 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=100)),
                ('gender', models.IntegerField(default=0)),
                ('types', models.IntegerField(default=1)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('createTime', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=100)),
                ('gender', models.IntegerField(default=0)),
                ('major', models.CharField(max_length=20)),
                ('types', models.IntegerField(default=0)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('createTime', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherandStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_flag', models.IntegerField(default=0)),
                ('student_flag', models.IntegerField(default=0)),
                ('start_role', models.IntegerField(default=0)),
                ('createTime', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('oTime', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='最后时间')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Student')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Teacher')),
            ],
        ),
    ]
