# Generated by Django 2.2.7 on 2020-02-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='gender',
            field=models.IntegerField(max_length=5),
        ),
    ]
