# Generated by Django 2.2.7 on 2020-02-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20200227_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='gender',
            field=models.CharField(max_length=5),
        ),
    ]
